clearml/clearml

- trains/binding/frameworks/tensorflow_bind.py
> fix vdict keys

- examples/autokeras/autokeras_imdb_example.py
> Add autokeras example

- setup.py
> remove six and pathlib2 dependencies from setup.py

- examples/frameworks/pytorch/pytorch_tensorboard.py
- examples/frameworks/tensorboardx/pytorch_tensorboardX.py
`batch_size=args.batch_size` --> `batch_size=args.test_batch_size` for `test_loader`
> bug: test_loader was using train batch_size instead of test_batch_size

- README.md
Hi!
Thanks for reaching out to us about the integration of Optuna into Trains. Glad to see Optuna is helpful!
Here's a badge to show that Optuna is built in. If there are other ways to let allegro.ai users know about Optuna, let us know.
Thanks!
> Add Optuna Integrated badge to README.md

- trains/binding/frameworks/tensorflow_bind.py
Fix saving image summary in trains dashboard.
Framework: tensorflow
> Fix in saving image summary in tensorflow bindings

- trains/task.py
allow to provide preview when upload artifact
> add option to control the artifact preview

- trains/binding/artifacts.py
- trains/task.py
> Added synchronous support for upload_artifact()

- examples/frameworks/ignite/cifar_ignite.py
- trains/storage/manager.py
Also fixed a bug in manager.py in _extract_to_cache function where Null name variable would cause crash when calling 
name = encode_string_to_filename(name)
> Add cifar ignite example and add auto extract of tar.gz files when using storagemanager

- docs/clearml-task.md
- examples/advanced/multiple_tasks_single_process.py
Task example added to show how to create multiple tasks in a single code. 
Changes made to clearml-task.md docs.
> add Task example, and add changes to clearml-task.md

- examples/reporting/data_samples/config_yaml.yaml
- examples/reporting/model_config.py
* write example so configurations don't override each other
* Add Yaml file sample to connect to task
> rewrite model_config example

- clearml/backend_interface/task/task.py
add docstring about minimum length of project and task names when initializing task
> Add task.init docstring

- examples/frameworks/tensorboardx/moviepy_tensorboardx.py
change moviepy_tensorboardx example's task name, so it will be different from pytorch_tensorboardx's task_name
> change task_name in tensorboardX example

- clearml/task.py
- examples/frameworks/tensorboardx/moviepy_tensorboardx.py
Fix typo in Task docstring. Audition >>> Auditing
> Fix docstring typo

- examples/advanced/multiple_tasks_single_process.py
Add print statements to example so tasks will contain something
> Add print statement to example

- clearml/cli/data/__main__.py
add example of specifying multiple parents with clearml-data. 
Optional - Create new dataset >>> Optional
> add example to clearml-data help strings

- clearml/binding/frameworks/megengine_bind.py
- clearml/model.py
- clearml/task.py
- examples/frameworks/megengine/megengine_mnist.py
This PR supports a new deep learning framework named [MegEngine](https://github.com/MegEngine/MegEngine). 
Please kindly review.
Related issue #451
> feat(framework): support MegEngine model

- clearml/automation/scheduler.py
- examples/scheduler/cron_example.py
`task_id` >>> `schedule_task_id` in TaskScheduler examples so code works when copied
> edit parameter in example docstring

- examples/frameworks/pytorch/notebooks/table/download_and_preprocessing.ipynb
- examples/frameworks/pytorch/notebooks/table/download_and_split.ipynb
- examples/frameworks/pytorch/notebooks/table/pick_best_model.ipynb
- examples/frameworks/pytorch/notebooks/table/preprocessing_and_encoding.ipynb
- examples/frameworks/pytorch/notebooks/table/tabular_ml_pipeline.ipynb
- examples/frameworks/pytorch/notebooks/table/train_tabular_predictor.ipynb
Add explanations about pipeline files in Jupyter Notebook: tabular_ml_pipeline, preprocessing_and_encoding, train_tabular_predictor, pick_best_model. 
Did black formatting for all files in folder
> Add Markdown in pipeline jupyter notebooks

- examples/services/monitoring/slack_alerts.py
Heya! First PR here -- I can't find any specific code reivew guidelines so I hope this is fine 😉 
This PR contains:
- Fix simple import statements for [Slack](https://slack.dev/python-slack-sdk/v3-migration/index.html#from-slackclient-2-x):
> The PyPI project is renamed from slackclient to slack_sdk
Importing slack_sdk.* is recommended. You can still use slack.* with deprecation warnings for a while.
- Add the concept of filters to SlackMonitor; essentially a list of callables that accept a `Task` object and return a boolean. Each such filter should decide if the given task should be filtered away (return `True`) or should it not be filtered (return `False`).
- Add arguments for filtering tasks by specific users. This is useful for example to ignore tasks by `Default User` (i.e. a test …
> Fix and upgrade the SlackMonitor

- clearml/storage/helper.py
- setup.py
Related issue: https://github.com/allegroai/clearml/issues/492
> support newer azure storage python version

- examples/pipeline/pipeline_from_decorator.py
Changed example pipeline_from_decorator.py to run locally
> minor changes on example

- examples/frameworks/pytorch-lightning/pytorch_lightning_example.py
- examples/frameworks/pytorch-lightning/requirements.txt
Run successfull on Python 3.7, 3.8, 3.9, 3.10
> Pytorch lightning example is updated

- docs/datasets.md
> Edit README

- examples/frameworks/openmmlab/openmmlab_cifar10.py
Refactored to match with other examples.
> Refactored OpenMMLab example

- examples/datasets/data_ingestion.py
> Modify clearml-data example task name

- examples/optimization/hyper-parameter-optimization/hyper_parameter_optimizer.py
Set reporting period to 0.2 minutes to match comment
> Edit example

- clearml/datasets/dataset.py
https://github.com/allegroai/clearml/issues/819
The threadpool futures are checked for exceptions instead of being ignored.
Repeat the "steps to reproduce" in the issue and verify that the script exits with a ValueError
With this change, on error (and exit) the dataset is left in state "Uploading" in the UI
> raise error on failed uploads

- README.md
- clearml/datasets/dataset.py
- examples/hyperdatasets/README.md
- examples/hyperdatasets/data-registration/register_dataset_masks.py
- examples/hyperdatasets/data-registration/register_dataset_with_roi.py
Edit Hyperdataset examples:
* Fix typos in README
* Fix incorrect information
* Fix script paths to run examples in command line
* Remove non-existent args in command line
* Correct `register_dataset_masks`'s description to reflect what example does
> Edit hyperdataset examples

- README.md
- clearml/automation/controller.py
- clearml/automation/job.py
- clearml/automation/optimization.py
- clearml/backend_api/services/v2_13/tasks.py
- clearml/backend_api/services/v2_20/tasks.py
- clearml/backend_api/services/v2_9/models.py
- clearml/backend_api/services/v2_9/tasks.py
- clearml/backend_interface/task/task.py
- clearml/datasets/dataset.py
- clearml/model.py
- clearml/task.py
Edit docstrings:
* Add spacing in docstrings to fix rendering
* Edit typos (id/Id >>> ID/s, hyper-parameter >>> hyperparameter)
> Edit docstrings

- clearml/backend_interface/task/task.py
Please check if the docstring is correct regarding its contents and its formatting.
> Improve the docstring of mark_completed

- clearml/binding/frameworks/tensorflow_bind.py
> PR relating to bug #923.

- clearml/task.py
https://app.slack.com/client/TT9ATQXJ5/CTK20V944/thread/CTK20V944-1676556098.205589
It was not clear to me, how close and mark_completed work.
Make sure that my documentation is correct. Not software test needed.
> Improve the docstring of close

- clearml/backend_interface/task/repo/scriptinfo.py
> Typo fix (to large -> too large)

- clearml/backend_interface/task/task.py
Related Issue \ discussion
References issue https://github.com/allegroai/clearml/issues/951.
Patch Description
Patch allows user to cast the parameter in get_parameter by passing the argument along to upstream get_parameters.
Testing Instructions
Unsure, should this have a unit test?
Other Information
This is my first PR to ClearML, I'd like to get more involved in contributing and would welcome any advice or feedback on my approach.
> Add a cast parameter to the get_parameter method of Task.

- clearml/backend_interface/task/task.py
See https://github.com/allegroai/clearml/issues/963
> #963: Modified documentation to reflect what actually happens

- clearml/backend_interface/task/task.py
- clearml/task.py
https://github.com/allegroai/clearml/issues/981
Provides better docstring.
> Update reference to GetAllRequest in Task

- clearml/binding/frameworks/pytorch_bind.py
fixes #1032
Adds model io patching for new lightning namespace
Use ClearML with new lightning namespace.
Without the fix no models will be uploaded to the tracking server, after the fix models will appear as expected.
> add support for new lightning namespace

- clearml/automation/controller.py
- clearml/logger.py
- clearml/task.py
This patch corrects spelling, a little code formatting, but mainly adds deprecation warnings to logger methods.
> Correct spelling, code formatting, add deprecation warnings to logger methods

- clearml/storage/helper.py
A user can specify the multipart threshold and chunksize in the ClearML config.
https://github.com/allegroai/clearml/issues/1058
Title says it all.
N/A
> Added boto3 parameters for multipart configurations

- clearml/datasets/dataset.py
Closes #1130 
https://github.com/allegroai/clearml/issues/1130
Processes file verification in parallel.
Ensure behaviour is same as single-threaded implementation.
> Verify dataset in parallel

- docs/tutorials/Getting_Started_3_Remote_Execution.ipynb
https://github.com/allegroai/clearml/issues/1204
Bug mentioned in original conversation.
This PR ensures that diff is empty and you can actually run the example provided.
NB, this is not an ideal fix because in theory the diff could contain additional useful changes.
However it does fix the immediate problem of running the tutorial e2e.
Open in Colab, ensure that the e2e examples still work.
> Fix Colab docs

- clearml/automation/auto_scaler.py
This patch is motivated by this discussion [Issue 1202](https://github.com/allegroai/clearml/issues/1202)
The patch double check that the worker is indeed still IDLE before spinning it down. The list of IDLE worker is refreshed at the beginning of the event loop and by that point it might not be accurate anymore.
Launching the autoscaler with max_idle_time=60s and queuing job at 60s interval - at some point some job gets picked up and the agent still get killed. 
As mention in the issue, this does not strictly solve the problem as the agent could picked up a task while the instance is being spinned down but it makes it less likely.
> :bug: Recheck that the worker is still IDLE before taking it down

- clearml/datasets/dataset.py
https://github.com/allegroai/clearml/issues/1227
Make dataset preview in the UI optional.
> Make dataset preview optional.

- clearml/automation/controller.py
Fixes https://github.com/clearml/clearml/issues/1406
> Fix argument order mismatch in PipelineController
