clearml/clearml

trains/model.py

Usually `.pt` is used as pytorch's extension, see [this StackOverflow question](https://stackoverflow.com/questions/59095824/what-is-difference-between-pt-pth-and-pwf-extentions-in-pytorch).
Furthermore `.pth` is used by Python to list additional package search paths (see [this PyTorch issue](https://github.com/pytorch/pytorch/issues/14864)) so IMO it might be worth to reconsider whether `.pth` should exist. AFAIK `.pt` is advised and used throughout most projects.

Add .pt file extension as PyTorch

---

trains/backend_interface/metrics/reporter.py
trains/backend_interface/task/task.py
trains/task.py

Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

---

trains/backend_interface/metrics/events.py

Fixes DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.

address DeprecationWarning

---

trains/backend_interface/task/task.py

Add set_parent method to Tasks.
Usage:
```
parent_task_id = "..."
task = Task.init(...)
print(task.parent)  # None
task.set_parent(parent_task_id)
assert task.parent == parent_task_id
```
Note: should be even better to have a `parent` parameter inside the Task.init() constructor.

Add set_parent method to Tasks

---

trains/task.py

This PR extends Task with the following function:
```
def wait_for_status(self, status=(tasks.TaskStatusEnum.completed),
raise_on_status=(tasks.TaskStatusEnum.failed),
check_interval_sec=60)
```
Use case: in a controller, it is handy to do as follows:
```
cloned_task = Task.clone(...)
cloned_task.connect(...)
cloned_task.enqueue(...)
cloned_task.wait_for_status(TaskStatusEnum.completed)
... # continue after task is finished
```

Add task.wait_for_status()

---

trains/utilities/resource_monitor.py

Robustify GPU monitoring. When a GPU is not selected, gpu memory must be computed only for the selected one.

Robustify GPU monitoring

---

requirements.txt

Installing `typing` on recent Python versions leads to the error described in python/typing#573 (running tests with tox yields `AttributeError: type object 'Callable' has no attribute '_abc_registry'`).
The [`typing` readme](https://pypi.org/project/typing/) suggests to install the package only for Python versions <3.5, which this commit does.

Only install typing dependency on Python<3.5

---

trains/storage/cache.py
trains/storage/manager.py

This PR introduces a flag for the `StorageManager.get_local_copy` named `force_download` which when set to `True` will overwrite existing cached files (default to `False`).
This flag is relevant for cases where the user modifies the local copy without uploading it, or when a file is updated on the remote repository and the user wishes to re-download it.
- `force_download` flag on `StorageManager.get_local_copy`.
- Bad usage of `Optional` type, `Optional` is for arguments that explicitly allow the value `None` and not for optional arguments as intuition might suggest ([reference](https://docs.python.org/3/library/typing.html#typing.Optional))
- Deletion of old files was dependent on modification time rather than access time, even though the sorting function was named `sort_max_access_time` …

Enable re-downloading cached files

---

trains/binding/frameworks/lightgbm_bind.py

Prevent error when user using keyword arguments instead of positional arguments
Related: #250 
lgb.train support positional arguments, but user can pass it as a keyword arguments. Previously code will fail if args is empty.
This fix attempt to catch positional arguments into `kwargs` if exist, so it can support both positional/keyword arguments.

Fix lightgbm binding keyword argument bugs

---

trains/backend_config/bucket_config.py
trains/backend_interface/setupuploadmixin.py
trains/storage/helper.py

allow to disable SSL certificates verification when using a Non-AWS S3 solution that only supports HTTPS with self-signed certificate.
ref: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html

Allow to disable SSL certificates verification when using a Non-AWS S3 solution

---

README.md

Change `task = Task(project_name='examples', task_name='hello world')` to `task = Task.init(project_name='examples', task_name='hello world')` to get rid of the following error:
```
clearml.errors.UsageError: Task object cannot be instantiated externally, use Task.current_task() or Task.get_task(...)
```

fix task init command in readme

---

clearml/backend_interface/task/repo/detectors.py

the results from git commands should be stripped only if they are **Not** diff (in the remote case it includes diff_remote and diff_remote_fallback)
see https://github.com/allegroai/clearml/issues/294

fix strip remote diff

---

clearml/datasets/dataset.py

Using the following script:
```from clearml import Dataset
dataset = Dataset.create(dataset_project='test', dataset_name='example')
dataset.add_files('/home/tglema/example.jpeg')
dataset.add_files('/home/tglema/logo.png')
print(dataset.list_files())
dataset.upload()
dataset.finalize()
dataset_new = Dataset.create(dataset_project='test', dataset_name='example_without_logo', parent_datasets=[dataset.id] )
print(dataset_new.list_files())
print(dataset_new.remove_files('logo.png'))
print(dataset_new.list_removed_files())
dataset_new.upload()
dataset_new.finalize()
```
I get this output:
> ['example.jpeg', 'logo.png']
Uploading compressed dataset changes (2 files, total 49.07 KB) to http://mvd0000xlrndtl2:8081
Upload completed (49.07 KB)
2021-02-05 17:04:38,333 - clearml.Task - INFO - Waiting …

fixed remove_files from Dataset class that did not match when files are in the root of the dataset

---

clearml/binding/hydra_bind.py

For compatibility in the upcoming Hydra change we update the binding to use keyword arguments when calling `run_job`.

Fix changes in Hydra binding for upcoming version.

---

clearml/backend_config/bucket_config.py
clearml/backend_config/config.py
clearml/config/default/sdk.conf
clearml/storage/helper.py
docs/clearml.conf
docs/trains.conf

Fixes #80 
Use the S3 keys specified in the config if they are available. 
Else, allow Boto to use its default credentials chain - https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

Use default boto credential chain if no keys in the config

---

examples/frameworks/tensorboardx/moviepy_tensorboardx.py

Currently, `writer.add_video("my_video", video, 0, fps=50)` produces broken still images. This is an example to facilitate support of `add_video`. When run you should see an video/gif that simply fades black to white and back in a loop.

Add a tensorboardx example for add_video (creates GIFs in tensorboard)

---

clearml/backend_interface/task/repo/scriptinfo.py

Get notebook auth token from the JUPYTERHUB_API_TOKEN environment variable if it is not present in the server info.
From our experience, notebooks spawned by JupyterHub do not provide an API token in their server info. In these cases, the clearml client is unable to integrate with Jupyter. This PR adds a fallback option to check the JUPYTERHUB_API_TOKEN environment variable if it can't find the API token otherwise. With this capability, we are able to integrate with notebooks spawned by a JupyterHub spawner.

Get notebook auth token from the JUPYTERHUB_API_TOKEN environment variable

---

clearml/datasets/dataset.py

Currently, since there are no outputs during the SHA2 generation phase, on big datasets this leads to misunderstanding that system is unresponsive.
Also, since server usually has a timeout of 2 hours before aborting unresponsive experiments, SHA2 generation phase can get aborted on server due to unresponsiveness.
This modification aims to seek both potential misunderstanding by users and server killing the task due to unresponsiveness by adding a loading bar with estimated time to finish.

Added loading bar to SHA2 generation

---

clearml/backend_interface/task/repo/scriptinfo.py

Fixes #442 
Explicitly sets to the default UTF-8 encoding while saving a jupyter notebook preview(from HTMLExporter).

Fix encoding while saving notebook preview

---

clearml/binding/frameworks/xgboost_bind.py

Per discussion in dev slack on 9/20/21, this fixes an issue that causes an error when xgboost is trained using keyword arguments.
For example, if [the example code](https://github.com/allegroai/clearml/blob/master/examples/frameworks/xgboost/xgboost_sample.py#39) is changed from
`bst = xgb.train(param, dtrain, num_round)`
to 
`bst = xgb.train(params=param, dtrain=dtrain, num_boost_round=num_round) `
We receive the following error:  `TypeError: _train() missing 1 required positional argument: '_PatchXGBoostModelIO__obj'`
This minor change fixes that issue.

Fix xgb train overloading

---

clearml/__init__.py
examples/pipeline/pipeline_from_decorator.py

Changes:
1. Add `TaskTypes` to main namespace 
2. Add task type declarations in pipeline decorator example

Add TaskTypes to Main Namespace

---

clearml/binding/environ_bind.py

Allows logging env vars starting with "*".
Example: 
`"*_THREADS"` would match:
```
OMP_NUM_THREADS
OPENBLAS_NUM_THREADS
MKL_NUM_THREADS
VECLIB_MAXIMUM_THREADS
NUMEXPR_NUM_THREADS
```

log env vars starting with * in environ_bind.py

---

clearml/datasets/dataset.py

Edit sync_folder doc string which included parameter `relative_base_folder` which was not a parameter in the method

edit sync_folder doc string

---

clearml/backend_interface/task/populate.py

Fixes a small Windows-only bug. 
Per #461, `"http://"` throws an `OSError` on Windows which is not handled by `Pathlib2` but returns False in `os.path`.

Search for Repo with OS to Avoid Windows Error

---

clearml/cli/config/__main__.py

It's specifically for use in Google Colab. A Colab instance always has the `COLAB_GPU` environment variable (this only one that's distinctive afaik). It even has the env var when you have a CPU or TPU runtime, in those cases it just says `COLAB_GPU=0`.
Fixes issue #514

Add better input handling for clearml-init in colab

---

clearml/automation/job.py
clearml/automation/optimization.py
examples/optimization/hyper-parameter-optimization/hyper_parameter_optimizer.py

Solves issue #520
Opted for a `run_locally()` method instead of adding the option as an argument to .run() because it is more inline with how ClearML pipelines manage the same functionality.
https://github.com/allegroai/clearml/blob/master/clearml/automation/controller.py#L703
-> Added the method, copied most of the docstring from .start() method, it also handles the same arguments
-> Changed LocalClearmlJob docstring to not only include the debugging usecase
-> Added the .start_locally() to the HPO example
Tested it locally, with GridSearch and Optuna. Callback function functionality works too.

Add LocalClearmlJob as possible option for HPO

---

clearml/backend_interface/util.py
clearml/datasets/dataset.py

Added some extra functionality to the `clearml-data` api to support the following use-case:
Say I have a data labeling flow. With as little lines of code as possible, I want to add functionality that quickly creates a new version of my labeled dataset based on the last version, that adds some new labeled samples. Just to keep track of my iterative updates to the dataset, be able to easily share the latest one and  not have to upload all samples every time.
To allow for this I made 3 changes:
1. Create a flag that implicitly creates a dataset and project while running `Dataset.get` if it does not exist yet.
In this way I don't have to either manually create a dataset when I want to start a new labeling process or first check if it exists with a `try catch` block around `Dataset.get` and …

Add some convenience functionality to clearml-data

---

examples/services/monitoring/requirements.txt

Cf [https://github.com/allegroai/clearml-server/issues/113](https://github.com/allegroai/clearml-server/issues/113)
Slack SDK requirement was out of date and `from slack_sdk import WebClient` was failing. This PR updates the requirement from `slackclient` to `slack_sdk` as per [the docs](https://slack.dev/python-slack-sdk/v3-migration/index.html#from-slackclient-2-x)

Update Slack SDK requirement

---

examples/clearml_agent/clearml_colab_agent.ipynb

In order for the agent to pull your code, it needs access to your repositories. If these are private, you'll have to supply the agent with github credentials to log in. Github/Bitbucket will no longer let you log in using username/password combinations. Instead, you have to use a personal token.
This PR adds how to do that as an optional cell.

Add git credentials to colab example

---

examples/frameworks/openmmlab/openmmlab_cifar10.py
examples/frameworks/openmmlab/requirements.txt

Resolves: #654
Add an OpenMMLab example and the example log can be found at https://app.clear.ml/projects/77e66ab064f74e4c89aacc2112cdf250/experiments/7638c3fdaf2e4fe896da32611c790fbe/output/execution
Note: Although this pr requires `mmcv>=1.5.1` and the latest version of mmcv is v1.5.0, we can build mmcv from source to use `ClearMLLoggerHook`. More details at https://github.com/open-mmlab/mmcv/pull/1906.

[Examples] Add openmmlab examples

---

clearml/datasets/dataset.py

Hello!
We had a [discussion](https://clearml.slack.com/archives/CTK20V944/p1650467326569479) on Slack about a new feature which added support for parallel downloads and extraction of datasets. Using multithreading was supposed to decrease the time which we need to obtain a local dataset copy by unzipping chunks of datasets in the background simultaneously with download. It seems to me that this feature is not working as expected.
So, previously the downloading of each particular dataset was conducted consequently, chunk by chunk. We used to download a chunk of data, extract it right after downloading ends and only after that take another chunk. The problem with that approach was that we were waiting a lot of time during zip extraction, which could be spent on downloading the next chunk. …

Fix dataset download

---

clearml/storage/helper.py

Explicitly specify an endpoint_url when creating S3 resource service for aws compatible bucket.
Fix [issues/673](https://github.com/allegroai/clearml/issues/673)

Specify an endpoint_url when creating S3 resource service

---

clearml/datasets/dataset.py
clearml/storage/cache.py

Ref: https://github.com/allegroai/clearml/issues/671
Basically, two main changes:
1. once the download of a dataset is completed, the lock is released immediately
2. while a process is downloading a dataset i.e. holding the lock, other processes will wait until the lock is released (in the current fix, after 5 min of wait there's a timeout error raise. But this can be changed)

Release lock after dataset cache is downloaded 

---

clearml/task.py

Following conversation in Slack, I couldn't find where in the documentation it says that `Task.init()` just returns the current task (ignoring any arguments given to it) when being executed remotely by a clearml-agent, so added it to the docstring.

Update Task.init docstring to include behaviour when executing remotely

---

examples/reporting/image_reporting.py

Examples points resources using relative paths
No yet
The example needs to points the folder of the resources in an absolute way.
Execute the examples from a location where the file is not.

Issues with relative paths in examples

---

clearml/datasets/dataset.py

[Slack thread](https://app.slack.com/client/TT9ATQXJ5/CTK20V944/thread/CTK20V944-1666866226.167449)
Fixed a bug where passing compression=ZIP_STORED (or 0) to Dataset.upload() uses ZIP_DEFLATED despite the user-supplied argument
upload any dataset and check if the resulting artifact is zip compressed or not.

dataset compression bug fix

---

clearml/storage/helper.py

https://github.com/allegroai/clearml/issues/840
https://clearml.slack.com/archives/CTK20V944/p1669932989917539
If an invalid a non service account credentials json is provided to the credentials, the GCS client will fail to be created, this happens when developing locally.
When passing `credentials=None` to `storage.Client()` it will fetch the environment variable `GOOGLE_APPLICATION_CREDENTIALS` as they recommend.
The original bug most likely stems from `bucket_config.py` setting the credentials via the global variable described above.
1. Authenticate your local Google Cloud environment as described in the [Google Documentation](https://cloud.google.com/docs/authentication/provide-credentials-adc).
2. Create a ClearML Dataset with an output_uri set to a GCS bucket location you have …

840: Set GCS credentials to None if invalid service account creds provided

---

clearml/storage/helper.py

Fixes allegroai/clearml#825
Adds a call to `StorageHelper._canonize_url(path)` in the `StorageHelper.get_object(...)` function.
This enables `StorageHelper.delete(...)` and other functions using `StorageHelper.get_object(...)` to respect the path substitutions configured.
Configure a path substitution where the path before substitution is not accessible.
Calls to `StorageHelper.delete(...)` and `StorageHelper.check_write_permissions(...)` (which calls `delete(...)`) should still succeed

Make StorageHelper.get_object() call StorageHelper._canonized_url()

---

clearml/backend_api/session/jsonmodels/fields.py
clearml/utilities/pyhocon/config_tree.py

https://github.com/allegroai/clearml/issues/834
Avoiding `DeprecationWarning: invalid escape sequence \w` by ensuring all `re.match` strings are prefixed with `r` (raw string)
Very minor fix
None

Added r prefix to re.match strings

---

clearml/cli/data/__main__.py

See allegroai/clearml#822
Use the number of modified files along with the number of added and removed file in the check that determines whether to proceed or not with the sync operation.
Create a new version of a dataset by syncing with only modified files (no added and no removed files, just modified files).

Fix for dataset not getting synced when there are only modified files

---

clearml/backend_interface/task/task.py

Correct Task.project docstring. "Returns project name" >>> "Returns project ID"

Edit docstring

---

clearml/backend_interface/task/populate.py

Fix a bug that if `clearml` is specified as requirement with extras (e.g. `clearml[azure]`) it would not be identified as clearml when creating a new Task.
https://github.com/allegroai/clearml/issues/867
In the method that processes all specified requirements and looking for whether `clearml` package was included, added an extra split identifier to ensure to make sure presence of "extras" (i.e. `[...]`) does not influence determining whether `clearml` is included in requirements.
Create a Task with requirements or packages, and include a version of clearml with extras. Make sure `clearml` is not appended to list of requirements.

Add extra split identifier

---

clearml/storage/helper.py

[Issue Link](https://github.com/allegroai/clearml/issues/883)
I added a `signature_version` entry to the boto3 section of the s3 configuration. This allows a user to specify the signature version for their s3 storage backend.
Push artifacts through clearml to an s3 service with an older signature version, specifying the correct signature version in the clearml config.

Add signature version to boto3 config

---

clearml/storage/helper.py
clearml/storage/manager.py

Related to [this previous issue](https://github.com/allegroai/clearml/issues/825), I noticed a few more problems when using path substitutions together with datasets.
The patch makes both StorageHelper.list() and StorageHelper.exists_file() respect the path substitutions that are set up.
It also makes _get_object_size_bytes only use a special case for the boto driver if the result has the content_length attribute (therefore it is a boto s3 object), as the ListResult that will still occur in combination with the Boto3Driver only has the size attribute.
Finally it handles a problem where the get_metadata of the storage_manager will return the url for the objects with the canonized base url(i.e. with the local path substitutions applied), instead of the original remote_url. There might be a …

Bugfix for storage with path substitutions

---

clearml/logger.py

* set annotated cells (cells with text inside them) to be the default.
* removed the unused series argument from the signature.

updated logger.report_confusion_matrix.py

---

clearml/automation/controller.py

https://clearml.slack.com/archives/CTK20V944/p1671538941447289<br/>
Now one may specify things like `${pipeline.queue_name}` for `queue_name` and control the execution queue of each task via pipeline parameters.<br/>

parse queue name

---

.gitignore
clearml/binding/click_bind.py

Issue #902 
Remove None keys in _args
following codes can reproduce None keys from Click
```
import click
from clearml import Task  # type: ignore
def run():
cli = click.CommandCollection(sources=[test_cli])
cli()
@click.group("test")
def test_cli():
pass
@test_cli.command(name="test")
@click.option("--root", "-r", type=str, required=True, help="root directory")
def test(**kwargs) -> None:
Task.init(
project_name="Test",
task_name="test",
output_uri=kwargs["root"],
)
print(kwargs)
if __name__ == "__main__":
run()
```
In terminal:
```
python test.py test -r example
```

ignore None keys in click args

---

clearml/backend_interface/task/repo/scriptinfo.py

This patch aims to solve an issue with newer versions of JupyterLab Notebook containing the wrong API key inside of `jpserver-x.json` while the environment variable `JUPYTERHUB_API_TOKEN` contains the correct one.<br/>
Create a JupyterLab version 3.5.2
run a ClearML task while storing Jupyter Notebook as code instead of a remote git repository
`clearml.Repository Detection - WARNING - Failed accessing the jupyter server: 403 Client Error: Forbidden for url: http://jupyter:888/user/me/api/sessions`

jupyter api token patch

---

clearml/logger.py

Description:
`series` argument was removed but `self._touch_title_series(title, series)` was kept and it produces the error:
```
File "/opt/conda/lib/python3.9/site-packages/clearml/logger.py", line 654, in report_confusion_matrix self._touch_title_series(title, series) NameError: name 'series' is not defined
```
Related commit:
- https://github.com/allegroai/clearml/commit/da6f75363db8c9d1ad2032ab075916e409b1170f#r102003686

Fixed bug in `report_confusion_matrix` when `series` argument was removed

---

clearml/backend_interface/model.py
clearml/storage/helper.py

Added fix to store unsubstituted url for model. Otherwise in the clearml artifact view you would see the substituted url, which would make the artifacts inaccesible if the substitution is not necessary for the users of the Web UI or for other agents using different substitutions.
Regarding the implementation of this I am not so sure. I wanted to use the implementation with maximum backwards compatibility. But I am not sure if the code can't be simplified more, by instead moving canonize_url() into the _do_upload(). I was for example unable to see in which cases
```
if res:
result_path = quote_url(result_path)
```
would be false. If you think a different solution/implementation is better, please feel free to add it in this PR.
I also added a call to canonize_url for .delete(). Without …

Fixes for path substitution

---

clearml/utilities/pigar/reqs.py

Modified logic which parses github dependencies to include subdirectory functionality
https://github.com/allegroai/clearml/issues/946
Patch adds github subdirectory to path.
See Issue https://github.com/allegroai/clearml/issues/946. I have tested this locally and I believe it fixes the issue.

Bugfix for issue 946: git pip install invalid

---

examples/frameworks/openmmlab/openmmlab_cifar10.py

When "output_uri" is set to True, it uploads the Artifacts or Models to the ClearML Server.

Add "output_uri=True" in the hook config (openmmlab example)

---

clearml/automation/controller.py

master is broken due to this missing comma added in this commit:
https://github.com/allegroai/clearml/commit/a9d2abae5b8fb58e3e9761979c9f4e5c6048c250#diff-cb73fc1356a778dad9f7de801d5491871d3230dfc7df351e8ac64166dbe5993dR148 

Added bug fix for missing comma

---

clearml/datasets/dataset.py

Add option for faster .add_external_files() option
Add option for parallel external file download
add_external_files: Add the option for specifying one dataset_path per entry in source_url. This was multiple files with different dataset_paths can be added in one batch, otherwise the update of the dataset state introduces a huge overhead for large number of files with different dataset paths
Parameter max_workers_external_files: Allow a parallel download of external files (especially relevant for smaller files). For backwards compatibility, this is introduced as a new parameter. It could just use the value of the existing parameter if desired. I am not sure how the internal threadpool of the boto library plays together with this in the case of larger files. 
If this patch originated from a …

External files: Improve performance

---

clearml/backend_interface/task/task.py
clearml/task.py

* Modify docstrings to fix documentation rendering.  
* Modify spacing so bullets aren't rendered as code
* Task.init - output_uri and continue_last_task - put admonitions as regular text, to fix rendering 
* Fix typos

Edit docstrings

---

clearml/logger.py

Fixed typo in the Logger documentation... Google's GCS protocol is gs:// not gc://
- Issue: https://github.com/allegroai/clearml/issues/986
Changed protocol in doc comment to `gs://`
See: https://clear.ml/docs/latest/docs/references/sdk/logger/#set_default_upload_destination
n/a

Fix comment for storage scheme gs://

---

examples/frameworks/pytorch/notebooks/table/train_tabular_predictor.ipynb

Example in jupyter notebook dont work correctly
Fix typo in artifacts name

Fix typo "Categories per column"

---

clearml/cli/config/__main__.py

Closes: https://github.com/allegroai/clearml-server/issues/198
It would handle configurations when web app port is changed to a standard port for HTTP or HTTPS.
It allows configurations like:
web_server: http://clearml.xyz.local
api_server: http://clearml.xyz.local:8008
file_server: http://clearml.xyz.local:8081/

Handle web app on standard HTTP and HTTPS port

---

clearml/backend_api/services/v2_20/projects.py
clearml/backend_api/services/v2_23/projects.py

Fixes typo in projects docstring `existis -> exists`<br/>

Fix typo in projects docstring

---

clearml/datasets/dataset.py

Related issue:
https://github.com/allegroai/clearml/issues/1067
* Added the option include_archived to Dataset.list_datasets() class method which, if False, will exclude archived datasets from the list. Defaults to True to maintain the current behavior of the class method. While it's possible to filter datasets using the get() class method it wasn't possible to do the same for the list_datasets() method. This feature seems useful to include and it's a simple, non-breaking modification.
* Updated formatting (whitespaces/spaces after comma/line breaks) in accordance with the flake8 formatting checks for dataset.py. As suggested in the contribution guidelines, fake8 was used to validate the formatting. Several errors were found from prior commits that were fixed.
Dataset.list_datasets(..., …

Added `include archive` to optionally exclude archived datasets from dataset.list datasets()

---

.github/workflows/codeql-analysis.yml

In your CI workflows you can see warning:
`This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/`
This patch should mitigate this

Bump version of codeql task

---

clearml/automation/aws_driver.py

N/A
- Fixes AWS credential access that uses a token - existing code does not take into consideration AWS credentials that use key/secret/token triplet to access resources.
- Fixes instantiation within VPC without AvailabilityZones. In these situations you must supply a SubnetID instead of AvailabilityZone.
- Extends EBS volume creation to include existing volumes (specified by `ebs_snapshot_id`). Note: In current code implementation EBS is attached but never mounted.
Credential authentication fails when attempting to use key/secret/token (due to the obvious lack of ability to specify a token)
SubnetID is a required parameter in certain VPC configurations where Availability Zones are not configured.

AWS driver fixes

---

clearml/datasets/dataset.py

Addresses behavior of the project of a dataset being hidden when dataset name is an empty string.
If the dataset project happens to match an existing project, it can be quite jarring to have one's history of experiments suddenly become hidden / make one think they "disappeared" (shown when hidden files enabled in UI, but new tasks can't point to the project name anymore).
If there's an intent behind this behavior (allowing empty dataset names), please let me know and I'd gladly change it to a warning instead.
Perhaps another solution is `dataset_name = None if dataset_name == ""`? or modify the project name under this condition so it's got some ephemeral name to it and prevents the behavior of an existing project getting wiped out.
Let me know if a minimal example to reproduce the …

raise error if dataset name empty.

---

clearml/automation/controller.py

https://github.com/allegroai/clearml/issues/1089
Adds support when using `PipelineController.add_step()`. Currently, it's impossible to parse anything besides strings with `_parse_step_ref()` in `parameter_override`. This patch allows list, dics, and tuples to be recursively parsed for step reference substitution. Since recursive features can add computational complexity the new feature is hidden behind a flag that can be passed when adding a step, which makes this a non-breaking change. 
If `recursively_parse_parameters=True` in `PipelineController.add_step()`, recursively parse parameters from parameter_override in lists, dicts, or tuples. 
Examples:
- ``parameter_override={'Args/input_file': ['${<step_name>.artifacts.<artifact_name>.url}', 'file2.txt']}`` will be correctly parsed.
- …

Add support for recursive list, dict, and tuple ref parsing for pipeline controller.add step() parameter override

---

clearml/binding/frameworks/lightgbm_bind.py

https://github.com/allegroai/clearml/issues/1135
Allow loading of a LightGBM model from a string instead of from file.
Try the code in the original issue with and without this change.

Allow lightgbm model loading from a string instead of file

---

clearml/storage/helper.py

When running a cloned task remotely and using GS as storage, calling `task.logger.set_default_upload_destination` usually fails with an error like:
```
GET https://storage.googleapis.com/storage/v1/b/clearml/project_a/.pipelines/Main/task_1.d7691550c955409db4622fd74496f51c/artifacts/result_TRAIN_config/result_TRAIN_config.pkl/iam/testPermissions?permissions=storage.objects.get&permissions=storage.objects.update&prettyPrint=false: Not Found
```
This is because the permissions are being tested on a single file instead of a GS bucket. Removing the `subdir` from the bucket url should fix it.
- Run a pipeline with a single task that calls `task.logger.set_default_upload_destination`
- Clone the task and enqueue it again for execution

Remove `subdir` path from GCP bucket url

---

clearml/backend_api/session/request.py
requirements.txt

N/A<br/>
Address the DeprecationWarning raised from `jsonschema`. My VSCode testing configuration treats DeprecationWarnings as Error, which means I cannot run any tests with VSCode testing when having clearml installed.
```
E   DeprecationWarning: Importing FormatError directly from the jsonschema package is deprecated and will become an ImportError. Import it from jsonschema.exceptions instead.
```
```python
>>> import jsonschema
>>> jsonschema.FormatError
<stdin>:1: DeprecationWarning: Importing FormatError directly from the jsonschema package is deprecated and will become an ImportError. Import it from jsonschema.exceptions instead.
<class 'jsonschema.exceptions.FormatError'>
```

address DeprecationWarnings from jsonschema

---

clearml/automation/controller.py

When a pipeline step is called multiple times, if a `pre_execute_callback`, `pre_execute_callback` or `status_change_callback` is set, it is called only the first time.
Minimal example:
```python
from clearml import PipelineDecorator
def pre_callaback(pipeline, node, parameters):
print(node.name)
@PipelineDecorator.component(name='step', pre_execute_callback=pre_callaback)
def step(i: int):
return i + 1
@PipelineDecorator.pipeline(name='test', project='test')
def pipeline():
for i in range(5):
step(i)
if __name__ == '__main__':
PipelineDecorator.run_locally()
pipeline()
```
This will print `step` only once, while I would expect to see it 5 times.
With this patch, the callbacks are copied to each node replica, and the output shows:
```
step
step_1
step_2
step_3
step_4
```

Fix missing component callbacks on multiple step calls

---

clearml/storage/helper.py

After https://github.com/allegroai/clearml/commit/b78e9b904742073b30558ee06d417770aed0bc4d, secure is now default to `True`. We need to forward `secure` key otherwise, even if it has been set to `False`, it switches back to `True`.
At https://github.com/allegroai/clearml/blob/0594a5ac8504d090bb851265f4f5c02c8d862dde/clearml/storage/helper.py#L2069
`secure` key is correctly fetched from the config file.
When `self._conf.update` is called right after, `secure` is automatically changed to `True`.
Install latest version of clearml (1.14.3). Try with `secure: false` in `clearml.conf` under `aws.s3.credentials`.
You should get a similar error:
```
[...]
File "/usr/local/lib/***3.8/site-packages/botocore/retryhandler.py", line 233, in __call__
return self._check_caught_exception(
File …
```

fix: :bug: forward `secure` in StorageHelper for s3

---

clearml/backend_interface/task/repo/scriptinfo.py

https://github.com/allegroai/clearml/issues/1207
Set utf-8 encoding for reading the script code
Successfully tested on the script attached to the issue

Fix UTF-8 script code encoding issue (#1207)

---

clearml/automation/controller.py

Added an option to allow the end user to create a pipeline step as a draft instead of it being automatically enqueued. This enables us to create pipelines where the parameters can be edited by a user before execution i.e. selecting the models to run in a testing step which can only be known once the training step has completed.
```
from clearml import PipelineController
def func(user_input):
print('This step has been executed!')
return user_input
if __name__ == '__main__':
pipe = PipelineController(
name='development',
project='testing',
version='0.1',
)
pipe.add_function_step(
name='run_immediately',
function=func,
function_kwargs={'user_input': 'Hello World!'},
function_return=['user_input'],
)
pipe.add_function_step(
name='draft',
function=func,
function_kwargs={'user_input': 'Hello …
```

Add option to create pipeline step as draft task

---

clearml/binding/frameworks/pytorch_bind.py

See #1249.<br/>
This patch adds more precise error handling and recovery for attribute errors encountered when accessing module or class attributes whose existence depends upon the version of `pytorch-lightning` installed.
The patch also deduplicates some code between `PatchPyTorchModelIO._patch_lightning_io` and `PatchPyTorchModelIO._patch_pytorch_lightning_io`.<br/>
Without the patch applied, train a model with `pytorch-lightning-2.0.0` or greater and save a checkpoint, which should automatically be uploaded to the ClearML server if the task is configured to do so.
Trying to resume training from the checkpoint will not work as the patch for loading models cannot be applied.
With the patch applied, training should resume as expected.

Fix issue #1249 pytorch-lightning patches

---

clearml/storage/helper.py

Fix for #1233. See also #1217.
Perform url canonization in `StorageHelper.get_driver_direct_access()`. It is performed in all relevant methods on `StorageHelper`: [here](https://github.com/allegroai/clearml/blob/e6e628517a865c5c1195ef5d661efc54437ac9e7/clearml/storage/helper.py#L2442) and [here](https://github.com/allegroai/clearml/blob/e6e628517a865c5c1195ef5d661efc54437ac9e7/clearml/storage/helper.py#L2487) and [here](https://github.com/allegroai/clearml/blob/e6e628517a865c5c1195ef5d661efc54437ac9e7/clearml/storage/helper.py#L2554) and [here](https://github.com/allegroai/clearml/blob/e6e628517a865c5c1195ef5d661efc54437ac9e7/clearml/storage/helper.py#L2606) and [here](https://github.com/allegroai/clearml/blob/e6e628517a865c5c1195ef5d661efc54437ac9e7/clearml/storage/helper.py#L2742) and …

Fix path substitution for file:// URIs

---

clearml/binding/fire_bind.py

Check #1268
ClearML reassignes python-fire function [`_CallAndUpdateTrace`](https://github.com/google/python-fire/blob/6902939a317dca9d41446168d8e88f108e0c0f11/fire/core.py#L660) with the [`_patched_call`](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/fire_bind.py#L62) wrapper call result. The first argument of `_patched_call` is `_CallAndUpdateTrace` itself and the second is [`__CallAndUpdateTrace`](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/fire_bind.py#L164) from ClearML.
In the end, original function is [passed](https://github.com/allegroai/clearml/blob/54418060ae94179a35bfef00c83c292ebfa5f13d/clearml/binding/frameworks/__init__.py#L34) to the `__CallAndUpdateTrace` with all …

Fix python-fire integration (issue #/1268)

---

clearml/config/default/sdk.conf
docs/clearml.conf
docs/trains.conf

Issue #1280
In the default configuration file for the SDK, the `retry_backoff_factor_sec` option has a comment that states it is the `Backoff factory...` instead of `Backoff factor...`.
This patch replaces the word `factory` with `factor` in three files: [sdk.conf](https://github.com/allegroai/clearml/blame/b5a1299ac7860d1b64412199f6e7a5db84abd3bb/clearml/config/default/sdk.conf#L61), [clearml.conf](https://github.com/allegroai/clearml/blame/b5a1299ac7860d1b64412199f6e7a5db84abd3bb/docs/clearml.conf#L81), and [trains.conf](https://github.com/allegroai/clearml/blame/b5a1299ac7860d1b64412199f6e7a5db84abd3bb/docs/trains.conf#L67).
No testing is required. The change is purely semantic.
I noticed this while reviewing the default configuration in my Python clearml sdk installation. I couldn't …

Fix typo in docs and default sdk config

---

clearml/binding/fire_bind.py

See #1300 
Wraps Fire call with `_patched_call_no_recursion_guard` instead of `_patched_call`. This allows other functions wrapped with `_patched_call` to be used under the Fire scope as intended.
Detailed code examples and discussion could be find in the related issue.

Fix `_patched_call` using along with Python Fire 

---

clearml/cli/data/__main__.py

When formatting the output for clearml-data search cli, if the version is None, the code throws an error. Fixed it by assigning an empty "" when the dataset version is None.
[#1321 ]
Assigning the dataset version to empty string if it is None when formatting the output.
Tested in Windows environment. The datasets are getting listed as expected.

clearml-data search formatting error fix

---

examples/frameworks/huggingface/transformers.ipynb

n/a
transformers trainer by default reports to all supported frameworks, so when ran the notebook, it asked for another platform's credentials. Added to [TrainingArguments](https://huggingface.co/docs/transformers/en/main_classes/trainer#transformers.TrainingArguments) `report_to=['clearml']` so it will only report to clearml.

Edit example

---

clearml/backend_api/session/session.py

This ensures that the module does not crash in case the logger was called when verbosity was not defined. Theold behaviour caused it to crash since `_logger` was `None`, but was still called anyways.
* Calculates a log level based on `self._verbose` (DEBUG/INFO when `verbose=True`, WARNING otherwise).
* Always assigns a valid logger instance, e.g.:
```python
self._logger = logger or get_logger(
level=level,
stream=sys.stderr if level is logging.DEBUG else None,
)
```
* Preserves existing behaviour:
* No extra output when `verbose=False`.
* Routes to `stderr` when `verbose=True`.
* Honours a user‑supplied logger without altering it.
* Fixes an unguarded call in `_do_refresh_token` that would execute:
```python
if not auth and not headers:
self._logger.warning(
"refreshing token with no …
```

fix: ensure _logger is not None in Session

---

clearml/datasets/dataset.py

When fetching the `project_ids`, some entries can be `None`, even though that should not happen. This causes the program to break. This patch adds defensive checks so that if a `None` value appears for a `project_id`, it is ignored and handled gracefully.
Listing all datasets from the CLI or from the SDK could trigger an error due to a `None` being possibly returned as one of the project IDs.
**SDK behaviour**
```python
>>> from clearml import Dataset
>>> Dataset.list_datasets()
Traceback (most recent call last):
File "<python-input-1>", line 1, in <module>
Dataset.list_datasets()
~~~~~~~~~~~~~~~~~~~~~^^
File "/home/amerii/projects/.../clearml/datasets/dataset.py", line 1972, in list_datasets
project_id_lookup = Task._get_project_names(list(project_ids))
File …
```

fix: Unhandled None value in project_ids when list all datasets

---

clearml/backend_config/config.py

Fixed typo in `backend_config/config.py` `of` -> `or`

fix: typo in config exception

---

setup.py

This PR addresses the issue with type checking tools (like `mypy`/`pyright`/`basedpyright`) reporting `Stub file not found` errors. The [type coverage analysis using mypy](https://github.com/user-attachments/files/20164431/mypy-report.txt) shows that ClearML's code has good type annotations coverage (especially the backend_api) with an overall coverage of > 88% , making it a good candidate for exposing type information through a `py.typed` marker.
This patch adds a `py.typed` marker file to expose existing type annotations to external tools that comply with [PEP 561](https://peps.python.org/pep-0561/). 
The changes:
1. Add an empty `py.typed` file to the main clearml package directory
2. Updated `setup.py` to include this file in package data
After applying the patch, typing tools like …

chore: add py.typed to support PEP 561 type checking
